- name: Provision the server
  hosts: all
  vars:
    config_files:
      - config.cfg
      - default.cfg
  pre_tasks:
    - set_fact:
        server_ip: "{{ ansible_eth0.ipv4.address }}"
    - include_vars: "{{ item }}"
      with_first_found: "{{ config_files }}"
  roles:
    - role: defaults
      tags:
        - always
    - role: common
    - role: unattended_upgrades
    - role: dns_encryption
    - role: wireguard
    - role: users
      tags:
        - users
