- name: Provision the server
  hosts: all
  pre_tasks:
    - name: Set IP address fact
      set_fact:
        server_ip: "{{ ansible_default_ipv4.address }}"
      tags:
        - always
    - name: Load custom config file
      include_vars: "{{ user_config_file }}"
      when: user_config_file is defined
      tags:
        - always
  roles:
    - role: defaults
      tags:
        - always
    - role: common
    - role: unattended_upgrades
    - role: dns_encryption
    - role: wireguard
    - role: users
      tags:
        - users
