- name: Provision the server
  hosts: all
  vars:
    config_files:
      - config.cfg
      - default.cfg
  pre_tasks:
    - name: Set IP address fact
      set_fact:
        server_ip: "{{ ansible_eth0.ipv4.address }}"
      tags:
        - always
    - name: Load config file
      include_vars: "{{ item }}"
      with_first_found: "{{ config_files }}"
      tags:
        - always
  roles:
    - role: defaults
      tags:
        - always
    - role: common
    - role: unattended_upgrades
    - role: dns_encryption
    - role: wireguard
    - role: users
      tags:
        - users
