- name: Provision the server
  hosts: localhost
  vars_files:
    - config.cfg
  pre_tasks:
    - set_fact:
        server_ip: "{{ ansible_eth0.ipv4.address }}"
  roles:
    - role: unattended_upgrades
    - role: common
    - role: dns_encryption
    - role: wireguard
    - role: users
      tags:
        - users
