- name: Raw update apt
  raw: apt update
- name: Raw install for python
  raw: apt install -y python3-pip
- name: Upgrade all packages
  apt:
    upgrade: dist
    update_cache: yes
    autoremove: yes
    autoclean: yes
- name: Install critical packages
  apt:
    name:
      - python3-dev
      - python3-pip
      - build-essential
      - git
      - vim-nox
- name: Install ansible
  pip:
    name: ansible
    executable: pip3
