- name: Resize filesystem
  command: resize2fs /dev/sda
- name: Remove old SSH host keys
  file:
    path: "{{ item }}"
    state: absent
  with_fileglob: '/etc/ssh/ssh_host*'
- name: Generate new host keys
  command: ssh-keygen -A
- name: Update sshd_config
  copy:
    src: sshd_config
    dest: /etc/ssh/sshd_config
    mode: 0640
    owner: root
    group: root
- name: Restart sshd
  service:
    name: sshd
    state: restarted
