- name: Resize filesystem
  command: resize2fs /dev/sda
- name: Remove old SSH host keys
  shell: rm -rf /etc/ssh/ssh_host*
  args:
    warn: false
- name: Generate new host keys
  command: ssh-keygen -A
- name: Remove swap device
  mount:
    src: /dev/sdb
    path: none
    fstype: swap
    state: absent
- name: Update sshd_config
  copy:
    src: sshd_config
    dest: /etc/ssh/sshd_config
    mode: 0640
    owner: root
    group: root
- name: Restart sshd
  service:
    name: sshd
    state: restarted
