---
- name: systemd services enabled and started
  systemd:
    name: "{{ item }}"
    state: started
    enabled: true
    daemon_reload: true
  loop:
    - systemd-networkd
    - systemd-resolved

- name: Install tools
  apt:
    name:
      - git
      - screen
      - apparmor-utils
      - uuid-runtime
      - coreutils
      - iptables-persistent
      - cgroup-tools
      - openssl
    state: present
    update_cache: true

- name: Install headers
  apt:
    name:
      - linux-headers-generic
      - "linux-headers-{{ ansible_kernel }}"
    state: present

- name: Loopback for services configured
  template:
    src: 10-algo-lo100.network.j2
    dest: /etc/systemd/network/10-algo-lo100.network
  notify:
    - restart systemd-networkd

- name: Iptables configured
  template:
    src: rules.v4.j2
    dest: /etc/iptables/rules.v4
    owner: root
    group: root
    mode: 0640
  notify:
    - restart iptables

- name: Sysctl tuning
  sysctl:
    name: "{{ item.item }}"
    value: "{{ item.value }}"
  loop:
    - item: net.ipv4.ip_forward
      value: 1
    - item: net.ipv4.conf.all.forwarding
      value: 1
